const frases = [
  "Razón número 1: Eres amable.",
  "Razón número 2: Eres autocrítico y siempre buscas mejorar.",
  "Razón número 3: Eres fuerte, incluso cuando te sientes débil.",
  "Razón número 4: Eres resiliente.",
  "Razón número 5: Amas intensamente.",
  "Razón número 6: Eres inteligente.",
  "Razón número 7: Propones dinámicas sociales sanas.",
  "Razón número 8: Te preocupas por los demás.",
  "Razón número 9: Eres sensible.",
  "Razón número 10: Tienes metas claras y la capacidad para alcanzarlas.",
  "Razón número 11: Siempre estás presente para quien te necesita (y por supuesto, lo merece).",
  "Razón número 12: No intentas cambiar a los demás.",
  "Razón número 13: Contigo los problemas se convierten fácilmente en soluciones.",
  "Razón número 14: Eres confiable.",
  "Razón número 15: Eres respetuosa y empática.",
  "Razón número 16: Eres admirable.",
  "Razón número 17: Eres graciosa y bastante ingeniosa.",
  "Razón número 18: Intentas entender a los demás y reconoces que hay múltiples realidades.",
  "Razón número 19: Eres un espacio seguro.",
  "Razón número 20: No solo dices las cosas, sino que actúas en consecuencia (eres coherente).",
  "Razón número 21: Contigo se puede construir un futuro seguro.",
  "Razón número 22: Inspiras a la mejora constante.",
  "Razón número 23: Entiendes y respetas las necesidades ajenas.",
  "Razón número 24: Contigo se siente como estar en familia.",
  "Razón número 25: Gracias a ti creo en el 'Para Siempre'.",
  "Razón número 27: Junto a ti no existe el miedo.",
  "Razón número 28: Tu paciencia.",
  "Razón número 29: Buscas crecer juntos, contigo no existe la envidia.",
  "Razón número 30: Eres leal.",
  "Razón número 31: Eres la prueba de que la amistad verdadera, sí existe.",
  "Razón número 32: Tu complicidad.",
  "Razón número 33: Siempre buscas hacer lo correcto, aunque no sea lo más fácil.",
  "Razón número 34: Escuchas para entender, no solo por oír.",
  "Razón número 35: Tu autenticidad.",
  "Razón número 36: Puedes convertir un momento cotidiano, en un recuerdo de por vida.",
  "Razón número 37: Eres lo suficientemente valiente y fuerte para mostrarte vulnerable.",
  "Razón número 38: Sabes cómo y cuándo pedir perdón y no solo eso, sino que intentas mejorarlo.",
  "Razón número 39: Nunca dejas de aprender.",
  "Razón número 40: Tu liderazgo.",
  "Razón número 41: Tienes una energía contagiosa y reconfortante.",
  "Razón número 42: Eres sociable.",
  "Razón número 43: Eres el tipo de persona que cualquiera desea tener a su lado.",
  "Razón número 44: Conviertes los errores y las experiencias negativas en aprendizajes.",
  "Razón número 45: No necesitas palabras para demostrar amor.",
  "Razón número 50: Te preocupas por y no olvidas los pequeños detalles.",
  "Razón número 51: Sabes ver lo bueno en otros.",
  "Razón número 52: Defiendes lo que te parece justo.",
  "Razón número 53: No dejas de amar, aunque te hayan hecho daño.",
  "Razón número 54: Acompañas en silencio cuando se necesita y no invalidas a los demás.",
  "Razón número 55: Valoras lo profundo.",
  "Razón número 56: Tu lealtad hacia ti misma y tus valores.",
  "Razón número 57: Por tu gran corazón, incluso aunque el mundo no lo merezca.",
  "Razón número 58: No dejas que los demás olviden su propio valor.",
  "Razón número 59: Dices la verdad cuando es necesario.",
  "Razón número 60: Comunicas abiertamente tus necesidades.",
  "Razón número 61: Enseñas y compartes sin juzgar.",
  "Razón número 62: Te tomas el tiempo de cuidar otros.",
  "Razón número 63: Sabes disfrutar de las cosas simples.",
  "Razón número 64: Tienes una memoria afectiva increíble.",
  "Razón número 65: Eres un ejemplo, sin proponértelo.",
  "Razón número 66: Transformas el dolor en fortaleza y crecimiento.",
  "Razón número 67: Incluso cuando no sabes qué decir o hacer, estás.",
  "Razón número 68: Sabes reírte de lo malo y sanar con humor.",
  "Razón número 69: Te acuerdas de lo que importa (aunque yo muchas veces me olvide).",
  "Razón número 70: Tienes una forma única de hacer sentir visible a los demás.",
  "Razón número 71: Sabes amar sin hacer ruido ni pedir nada a cambio.",
  "Razón número 72: Por tu constancia al amar.",
  "Razón número 73: Cuidas tus vínculos.",
  "Razón número 74: Siempre tienes las palabras indicadas en el momento justo.",
  "Razón número 75: Sabes regalar tiempo y no solo presencia.",
  "Razón número 76: Sabes recordar lo bueno del otro, incluso cuando no lo ven.",
  "Razón número 77: No te alejas cuando llega la tormenta.",
  "Razón número 78: Hablas con amar, pero siempre firme y honestamente.",
  "Razón número 79: Tu forma de cuidar. Es un lenguaje en sí mismo.",
  "Razón número 80: No tienes miedo a sentir.",
  "Razón número 81: Contigo se puede reir hasta quedarse sin aire, incluso de las cosas que pueden parecer absurdas.",
  "Razón número 82: Solo tú puedes escuchar audios que parecen podcast sin hacer sentir mal a los demás.",
  "Razón número 83: Sabes a quién odiar, sin decirte nada (a esos que lastiman a quienes te importan).",
  "Razón número 84: Contigo se puede simplemente SER.",
  "Razón número 85: Contigo hasta sacar la basura, es tremendo planazo.",
  "Razón número 86: Sabes transformar el dolor en risas.",
  "Razón número 87: A pesar de la distancia, me haces sentir como si vivieramos diariamente lado a lado.",
  "Razón número 88: Tu ética intachable.",
  "Razón número 89: Tus varias preguntas, que incitan al diálogo profundo y permiten afianzar la relación.",
  "Razón número 90: Nunca minimizas las emociones de otros, por pequeñas que parezcan.",
  "Razón número 91: Tienes un sexto sentido para saber cuando algo no está bien.",
  "Razón número 92: Sabes poner límites y en el proceso intentas no hacer daño.",
  "Razón número 93: Siempre tienes algo que aportar, incluso cuando sientes que no.",
  "Razón número 94: Sabes pedir ayuda, sin sentirte menos.",
  "Razón número 95: Te arriesgas a confiar.",
  "Razón número 96: Tu honestidad jamás duele, pero sí libera.",
  "Razón número 97: Cuidas tus relaciones y las deja ir cuando es debido.",
  "Razón número 98: Sabes hacer sentir a alguien, importante.",
  "Razón número 99: Sabes empezar de nuevo, sin perder lo que has aprendido.",
  "Razón número 100: Eres tú.",
];

document.getElementById("boton-frase").addEventListener("click", () => {
  const indice = Math.floor(Math.random() * frases.length);
  const fraseSeleccionada = frases[indice];
  document.getElementById("frase").textContent = fraseSeleccionada;
});
